#pragma once

enum XACT_WAVEBANK_MOVEBANK : unsigned int
{
    XACT_WAVEBANK_MOVEBANK_RUN = 0,
    XACT_WAVEBANK_MOVEBANK_JUMP = 1,
    XACT_WAVEBANK_MOVEBANK_JUMPLAND = 2,
    XACT_WAVEBANK_MOVEBANK_KNOCKDOWN = 3,
    XACT_WAVEBANK_MOVEBANK_HITSTUN = 4,
    XACT_WAVEBANK_MOVEBANK_WAVEDASH = 5,
    XACT_WAVEBANK_MOVEBANK_ROLL = 6,
    XACT_WAVEBANK_MOVEBANK_CROUCH = 7,
    XACT_WAVEBANK_MOVEBANK_DOUBLEJUMP = 8,
    XACT_WAVEBANK_MOVEBANK_AIRDASH = 9,
    XACT_WAVEBANK_MOVEBANK_FASTFALL = 10,
    XACT_WAVEBANK_MOVEBANK_TECH = 11,
    XACT_WAVEBANK_MOVEBANK_BOUNCE = 12,
    XACT_WAVEBANK_MOVEBANK_SHIELD = 13,
    XACT_WAVEBANK_MOVEBANK_DEATH = 14,
};

#define XACT_WAVEBANK_MOVEBANK_ENTRY_COUNT 15
