#pragma once

enum XACT_WAVEBANK_MUSICBANK : unsigned int
{
    XACT_WAVEBANK_MUSICBANK_GIRAFFEWARSTHEME = 0,
    XACT_WAVEBANK_MUSICBANK_WINTHEME = 1,
    XACT_WAVEBANK_MUSICBANK_MENUTHEME = 2,
};

#define XACT_WAVEBANK_MUSICBANK_ENTRY_COUNT 3
