#pragma once

enum XACT_WAVEBANK_TESTBANK : unsigned int
{
    XACT_WAVEBANK_TESTBANK_AIRDASH = 0,
    XACT_WAVEBANK_TESTBANK_BACKTHROW = 1,
    XACT_WAVEBANK_TESTBANK_BAIR = 2,
    XACT_WAVEBANK_TESTBANK_DAIR = 3,
    XACT_WAVEBANK_TESTBANK_DOWNB = 4,
    XACT_WAVEBANK_TESTBANK_DOWNTHROW = 5,
    XACT_WAVEBANK_TESTBANK_DSMASH = 6,
    XACT_WAVEBANK_TESTBANK_DTILT = 7,
    XACT_WAVEBANK_TESTBANK_FAIR = 8,
    XACT_WAVEBANK_TESTBANK_FSMASH = 9,
    XACT_WAVEBANK_TESTBANK_FTHROW = 10,
    XACT_WAVEBANK_TESTBANK_FTILT = 11,
    XACT_WAVEBANK_TESTBANK_GETUPATTACK = 12,
    XACT_WAVEBANK_TESTBANK_GRAB = 13,
    XACT_WAVEBANK_TESTBANK_HIT = 14,
    XACT_WAVEBANK_TESTBANK_JAB = 15,
    XACT_WAVEBANK_TESTBANK_JUMP = 16,
    XACT_WAVEBANK_TESTBANK_JUMPLAND = 17,
    XACT_WAVEBANK_TESTBANK_NAIR = 18,
    XACT_WAVEBANK_TESTBANK_NEUTRALB = 19,
    XACT_WAVEBANK_TESTBANK_ROLL = 20,
    XACT_WAVEBANK_TESTBANK_SIDEB = 21,
    XACT_WAVEBANK_TESTBANK_UPAIR = 22,
    XACT_WAVEBANK_TESTBANK_UPB = 23,
    XACT_WAVEBANK_TESTBANK_UPSMASH = 24,
    XACT_WAVEBANK_TESTBANK_UPTHROW = 25,
    XACT_WAVEBANK_TESTBANK_UPTILT = 26,
    XACT_WAVEBANK_TESTBANK_WAVEDASH = 27,
};

#define XACT_WAVEBANK_TESTBANK_ENTRY_COUNT 28


#define TESTBANK_AIRDASH_LENGTH 18
#define TESTBANK_BACKTHROW_LENGTH 25
#define TESTBANK_BAIR_LENGTH 11
#define TESTBANK_DAIR_LENGTH 13
#define TESTBANK_DOWNB_LENGTH 41
#define TESTBANK_DOWNTHROW_LENGTH 23
#define TESTBANK_DSMASH_LENGTH 11
#define TESTBANK_DTILT_LENGTH 8
#define TESTBANK_FAIR_LENGTH 12
#define TESTBANK_FSMASH_LENGTH 14
#define TESTBANK_FTHROW_LENGTH 29
#define TESTBANK_FTILT_LENGTH 13
#define TESTBANK_GETUPATTACK_LENGTH 29
#define TESTBANK_GRAB_LENGTH 24
#define TESTBANK_HIT_LENGTH 22
#define TESTBANK_JAB_LENGTH 9
#define TESTBANK_JUMP_LENGTH 17
#define TESTBANK_JUMPLAND_LENGTH 18
#define TESTBANK_NAIR_LENGTH 12
#define TESTBANK_NEUTRALB_LENGTH 21
#define TESTBANK_ROLL_LENGTH 24
#define TESTBANK_SIDEB_LENGTH 18
#define TESTBANK_UPAIR_LENGTH 10
#define TESTBANK_UPB_LENGTH 29
#define TESTBANK_UPSMASH_LENGTH 16
#define TESTBANK_UPTHROW_LENGTH 32
#define TESTBANK_UPTILT_LENGTH 12
#define TESTBANK_WAVEDASH_LENGTH 38









