#pragma once

enum XACT_WAVEBANK_TESTBANK : unsigned int
{
    XACT_WAVEBANK_TESTBANK_AIRDASH = 0,
    XACT_WAVEBANK_TESTBANK_BACKTHROW = 1,
    XACT_WAVEBANK_TESTBANK_BAIR = 2,
    XACT_WAVEBANK_TESTBANK_DAIR = 3,
    XACT_WAVEBANK_TESTBANK_DOWNB = 4,
    XACT_WAVEBANK_TESTBANK_DOWNTHROW = 5,
    XACT_WAVEBANK_TESTBANK_DSMASH = 6,
    XACT_WAVEBANK_TESTBANK_DTILT = 7,
    XACT_WAVEBANK_TESTBANK_FAIR = 8,
    XACT_WAVEBANK_TESTBANK_FSMASH = 9,
    XACT_WAVEBANK_TESTBANK_FTHROW = 10,
    XACT_WAVEBANK_TESTBANK_FTILT = 11,
    XACT_WAVEBANK_TESTBANK_GETUPATTACK = 12,
    XACT_WAVEBANK_TESTBANK_GRAB = 13,
    XACT_WAVEBANK_TESTBANK_JAB = 14,
    XACT_WAVEBANK_TESTBANK_JUMP = 15,
    XACT_WAVEBANK_TESTBANK_JUMPLAND = 16,
    XACT_WAVEBANK_TESTBANK_NAIR = 17,
    XACT_WAVEBANK_TESTBANK_NEUTRALB = 18,
    XACT_WAVEBANK_TESTBANK_ROLL = 19,
    XACT_WAVEBANK_TESTBANK_SIDEB = 20,
    XACT_WAVEBANK_TESTBANK_UPAIR = 21,
    XACT_WAVEBANK_TESTBANK_UPB = 22,
    XACT_WAVEBANK_TESTBANK_UPSMASH = 23,
    XACT_WAVEBANK_TESTBANK_UPTHROW = 24,
    XACT_WAVEBANK_TESTBANK_UPTILT = 25,
    XACT_WAVEBANK_TESTBANK_WAVEDASH = 26,
};

#define XACT_WAVEBANK_TESTBANK_ENTRY_COUNT 27
#define TESTBANK_AIRDASH_LENGTH 41
#define TESTBANK_BACKTHROW_LENGTH 59
#define TESTBANK_BAIR_LENGTH 62
#define TESTBANK_DAIR_LENGTH 62
#define TESTBANK_DOWNB_LENGTH 55
#define TESTBANK_DOWNTHROW_LENGTH 64
#define TESTBANK_DSMASH_LENGTH 57
#define TESTBANK_DTILT_LENGTH 56
#define TESTBANK_FAIR_LENGTH 85
#define TESTBANK_FSMASH_LENGTH 55
#define TESTBANK_FTHROW_LENGTH 62
#define TESTBANK_FTILT_LENGTH 66
#define TESTBANK_GETUPATTACK_LENGTH 58
#define TESTBANK_GRAB_LENGTH 25
#define TESTBANK_JAB_LENGTH 29
#define TESTBANK_JUMP_LENGTH 27
#define TESTBANK_JUMPLAND_LENGTH 38
#define TESTBANK_NAIR_LENGTH 63
#define TESTBANK_NEUTRALB_LENGTH 61
#define TESTBANK_ROLL_LENGTH 25
#define TESTBANK_SIDEB_LENGTH 79
#define TESTBANK_UPAIR_LENGTH 52
#define TESTBANK_UPB_LENGTH 69
#define TESTBANK_UPSMASH_LENGTH 70
#define TESTBANK_UPTHROW_LENGTH 65
#define TESTBANK_UPTILT_LENGTH 57
#define TESTBANK_WAVEDASH_LENGTH 50