#pragma once

enum XACT_WAVEBANK_TESTBANK : unsigned int
{
    XACT_WAVEBANK_TESTBANK_AIRDASH = 0,
    XACT_WAVEBANK_TESTBANK_BACKTHROW = 1,
    XACT_WAVEBANK_TESTBANK_BAIR = 2,
    XACT_WAVEBANK_TESTBANK_DAIR = 3,
    XACT_WAVEBANK_TESTBANK_DOWNB = 4,
    XACT_WAVEBANK_TESTBANK_DOWNTHROW = 5,
    XACT_WAVEBANK_TESTBANK_DSMASH = 6,
    XACT_WAVEBANK_TESTBANK_DTILT = 7,
    XACT_WAVEBANK_TESTBANK_FAIR = 8,
    XACT_WAVEBANK_TESTBANK_FSMASH = 9,
    XACT_WAVEBANK_TESTBANK_FTHROW = 10,
    XACT_WAVEBANK_TESTBANK_FTILT = 11,
    XACT_WAVEBANK_TESTBANK_GETUPATTACK = 12,
    XACT_WAVEBANK_TESTBANK_GRAB = 13,
    XACT_WAVEBANK_TESTBANK_JAB = 14,
    XACT_WAVEBANK_TESTBANK_JUMP = 15,
    XACT_WAVEBANK_TESTBANK_JUMPLAND = 16,
    XACT_WAVEBANK_TESTBANK_NAIR = 17,
    XACT_WAVEBANK_TESTBANK_NEUTRALB = 18,
    XACT_WAVEBANK_TESTBANK_ROLL = 19,
    XACT_WAVEBANK_TESTBANK_SIDEB = 20,
    XACT_WAVEBANK_TESTBANK_UPAIR = 21,
    XACT_WAVEBANK_TESTBANK_UPB = 22,
    XACT_WAVEBANK_TESTBANK_UPSMASH = 23,
    XACT_WAVEBANK_TESTBANK_UPTHROW = 24,
    XACT_WAVEBANK_TESTBANK_UPTILT = 25,
    XACT_WAVEBANK_TESTBANK_WAVEDASH = 26,
};

#define XACT_WAVEBANK_TESTBANK_ENTRY_COUNT 27
